import {
  packageManagerLabel,
  stackDatabaseDisplay,
  stackFrameworkDisplay,
} from "../detectors/labels.js";
import { runScriptCommand } from "../detectors/scripts.js";
import type { ProjectContext } from "../types.js";
import { oneTrailingNewline } from "./format.js";
import { formatTestingExpectations } from "./testing-expectations.js";

export function generateCursorRules(ctx: ProjectContext): string {
  const pmLabel = packageManagerLabel(
    ctx.packageManager,
    ctx.packageManagerSource,
  );
  const framework = stackFrameworkDisplay(ctx.stack);
  const database = ctx.stack.database ? stackDatabaseDisplay(ctx.stack) : null;

  const lines = [
    "---",
    "description: Agent context and safety rules generated by agent-context-kit",
    "alwaysApply: true",
    "---",
    "",
    "# Agent Context",
    "",
    `Project: ${ctx.name}`,
    `Package manager: ${pmLabel}`,
    `Framework: ${framework}`,
    ...(database ? [`Database: ${database}`] : []),
    "",
    "## Work Rules",
    "",
    "- Use commands from `COMMANDS.md` and scripts from `package.json`.",
    "- Keep changes small and focused.",
    "- Match existing code style and project structure.",
    "- Do not invent missing framework, database, or script details.",
    "- Do not edit lockfiles unless dependency changes are required.",
    "- Avoid `node_modules`, `.git`, `dist`, `build`, `.next`, and `coverage`.",
    "",
    "## Verification",
    "",
    formatTestingExpectations(ctx),
  ];

  const build = runScriptCommand(ctx.packageManager, "build");
  if (ctx.scripts.build) lines.push(`- Build command: \`${build}\`.`);
  if (ctx.scripts.test) {
    lines.push(
      `- Test command: \`${runScriptCommand(ctx.packageManager, "test")}\`.`,
    );
  }

  lines.push(
    "",
    "## Context Files",
    "",
    "- Read `AGENTS.md` for repository rules.",
    "- Read `PROJECT_CONTEXT.md` for stack and folder context.",
    "- Read `COMMANDS.md` for setup and verification commands.",
  );

  return oneTrailingNewline(lines.join("\n"));
}
