import { packageManagerLabel } from "../detectors/labels.js";
import {
  formatStackLayerSources,
  isStackEmpty,
  stackDatabaseSummary,
  stackFrameworkSummary,
  stackLayerLabel,
} from "../detectors/stack.js";
import { hasReadme } from "../fs/read-project.js";
import type { ProjectContext, ProjectStack, StackLayer } from "../types.js";
import { formatFolderBullets } from "./format.js";

function formatDeps(deps: Record<string, string>, limit = 15): string {
  const entries = Object.entries(deps);
  if (entries.length === 0) {
    return "Not detected";
  }
  const lines = entries
    .slice(0, limit)
    .map(([name, version]) => `- \`${name}\`: ${version}`);
  if (entries.length > limit) {
    lines.push(`- _…and ${entries.length - limit} more_`);
  }
  return lines.join("\n");
}

function formatStackLayerBlock(layer: StackLayer | undefined): string {
  if (!layer) {
    return "Not detected";
  }
  return `${layer.label}\n\n_Detected from dependencies:_ ${formatStackLayerSources(layer)}`;
}

function stackSection(stack: ProjectStack): string {
  if (isStackEmpty(stack)) {
    return "Not detected";
  }

  return `### Frontend

${formatStackLayerBlock(stack.frontend)}

### Backend

${formatStackLayerBlock(stack.backend)}

### Database

${formatStackLayerBlock(stack.database)}`;
}

export function generateProjectContextMd(ctx: ProjectContext): string {
  const folderBlock = formatFolderBullets(ctx.folders);

  const notes: string[] = [];
  if (!hasReadme(ctx.cwd)) {
    notes.push("- No `README.md` found in project root.");
  }
  if (ctx.packageManagerSource === "fallback") {
    notes.push(
      "- Package manager inferred as npm (no lockfile or packageManager field).",
    );
  }
  if (ctx.stack.backend) {
    notes.push(
      "- Backend dependencies were detected. Verify server entry points and deployment commands manually.",
    );
  }
  if (notes.length === 0) {
    notes.push("- Generated by `rfa init`. Re-run with `--force` to refresh.");
  }

  const summary = isStackEmpty(ctx.stack)
    ? "Not detected"
    : [
        `Frontend/Backend: ${stackFrameworkSummary(ctx.stack)}`,
        stackDatabaseSummary(ctx.stack) &&
          `Database: ${stackDatabaseSummary(ctx.stack)}`,
      ]
        .filter(Boolean)
        .join("; ");

  return `# PROJECT_CONTEXT.md

## Project Name

\`${ctx.name}\`

## Stack

${stackSection(ctx.stack)}

**Summary:** ${summary}

## Package Manager

${packageManagerLabel(ctx.packageManager, ctx.packageManagerSource)}

## Framework

${stackFrameworkSummary(ctx.stack)}

## Database

${stackLayerLabel(ctx.stack.database) ?? "Not detected"}

### Important Folders
${folderBlock}

## Agent Context Index

- \`AGENTS.md\`: agent rules, workflow, safety constraints, and verification expectations.
- \`PROJECT_CONTEXT.md\`: stack, package manager, folders, dependencies, and project notes.
- \`COMMANDS.md\`: setup, development, build, test, lint, typecheck, and format commands.
- \`.ready-for-agents/context-tree.json\`: compact generated section map for targeted context lookup when present.

## Dependencies

### dependencies

${formatDeps(ctx.dependencies)}

### devDependencies

${formatDeps(ctx.devDependencies)}

## Notes

${notes.join("\n")}
`;
}
